spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rae?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: c925445388
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  #mvc:
    #static-path-pattern: /**

server:
  port: 8888

